//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnolToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnolToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;~~Author~~.        Ian Morrish
        ///&apos;~~Email_Address~~. ian@glazier.co.nz
        ///&apos;~~Script_Type~~.   Vbscript
        ///&apos;~~Sub_Type~~. Misc
        ///&apos;~~Keywords~~.      ASCII, Character Set
        ///
        ///&apos;~~Comment~~.
        ///&apos;Displays the decimal number, ASCII character and character of desired Windows font in IE (allows for copy and paste).
        ///
        ///&apos;~~Script~~.
        ///
        ///&apos;==========================================================================
        ///&apos;
        ///&apos; VBScript Source File -- Created with SAPIEN Technologies PrimalSCRIPT(TM)
        ///&apos;
        ///&apos; Author: Characters.vbs
        ///&apos;
        ///&apos; A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCII_znaky {
            get {
                return ResourceManager.GetString("ASCII_znaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;===============================================================================
        ///&apos;
        ///&apos; This script demonstrates the retrieval of BitLocker Drive Encryption (BDE) 
        ///&apos; recovery information from Active Directory for a particular computer.
        ///&apos;
        ///&apos; It returns all recovery passwords and associated GUIDs for a particular 
        ///&apos; computer object.
        ///&apos;
        ///&apos; Last Updated: 5/15/2006
        ///&apos; Last Reviewed: 9/25/2009
        ///&apos;
        ///&apos;
        ///&apos; Microsoft Corporation
        ///&apos;
        ///&apos; Disclaimer
        ///&apos; 
        ///&apos; The sample scripts are not supported under any Microsoft standar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bitlocker {
            get {
                return ResourceManager.GetString("bitlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///  &lt;title&gt;Změna Skupin PC&lt;/title&gt; 
        ///&lt;HTA:APPLICATION 
        ///     ID=&quot;oGroupChange&quot;
        ///     APPLICATIONNAME=&quot;Change Local Groups&quot;
        ///     SCROLL=&quot;no&quot;
        ///     SINGLEINSTANCE=&quot;no&quot;
        ///     WINDOWSTATE=&quot;normal&quot;
        ///     icon=&quot;C:\Windows\SysWOW64\shrpubw.exe&quot; 
        ///     contextmenu=&quot;yes&quot;
        ///     sysmenu=&quot;yes&quot;
        ///     MINIMIZEBUTTON=&quot;yes&quot; 
        ///     caption=&quot;yes&quot;        
        ///     version [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Change_Groups {
            get {
                return ResourceManager.GetString("Change_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Account_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Account_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Admin_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Admin_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Admin_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Admin_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Administrative_Tools_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Administrative_Tools_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Close_Window_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Close_Window_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Command_Line_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Command_Line_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Command_Line_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Command_Line_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Computer_Find_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Computer_Find_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Computer_Find_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Computer_Find_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Crown_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Crown_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Crown_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Crown_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Data_Encryption_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Data_Encryption_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Data_Encryption_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Data_Encryption_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Key_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Key_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Key_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Key_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Laptop_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Laptop_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Laptop_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Laptop_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Lock_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Lock_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Message_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Message_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Message_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Message_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_Refresh_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_Refresh_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_Refresh_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_Refresh_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_Star_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_Star_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Monitor_Star_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Monitor_Star_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Name_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Name_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Name_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Name_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Name_Tag_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Name_Tag_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Name_Tag_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Name_Tag_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Network_Card_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Network_Card_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Network_Card_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Network_Card_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Processor_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Processor_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Processor_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Processor_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Registry_Editor_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Registry_Editor_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Registry_Editor_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Registry_Editor_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Remote_Control_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Remote_Control_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Remote_Control_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Remote_Control_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Restart_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Restart_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Restart_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Restart_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_SAP_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_SAP_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_SAP_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_SAP_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Server_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Server_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Server_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Server_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Settings_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Settings_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Settings_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Settings_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Software_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Software_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Software_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Software_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Software_Uninstaller_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Software_Uninstaller_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Software_Uninstaller_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Software_Uninstaller_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Support_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Support_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Support_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Support_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Table_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Table_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Table_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_Table_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_User_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_User_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_User_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_User_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_User_Group_Man_Man_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_User_Group_Man_Man_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_User_Group_Man_Man_96_white {
            get {
                object obj = ResourceManager.GetObject("icons8_User_Group_Man_Man_96_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_96px {
            get {
                object obj = ResourceManager.GetObject("Menu_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;tento skript je treba spustit s parametry! napr. &quot;jmenoSkriptu.vbs computername Notepad++&quot; - nize jsou popsany parametry co delaji
        ///&apos;objArgs(0) = computername
        ///&apos;objArgs(1) = aplikace, kterou hledame/odinstalovavame
        ///
        ///
        ///Set objArgs = Wscript.Arguments
        ///&apos;  True           - pouze uloží vásledky hledání
        ///&apos;  False          - ihned odinstaluje
        ///Dim ToFile: ToFile = True
        ///
        ///&apos;  &quot;.&quot;            - provede v PC, kde je script spuštěn
        ///&apos;  &quot;SKDATVxxyyyy&quot; - provede v definovaném PC
        ///Dim strComputer: strComputer = objArg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msi_vyhledavac {
            get {
                return ResourceManager.GetString("msi_vyhledavac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///  &lt;title&gt;PC Info (Online) &lt;/title&gt; 
        ///&lt;HTA:APPLICATION 
        ///     ID=&quot;oPCInfoSearchForm&quot;
        ///     APPLICATIONNAME=&quot;PC Info Search&quot;
        ///     SCROLL=&quot;no&quot;
        ///     SINGLEINSTANCE=&quot;no&quot;
        ///     WINDOWSTATE=&quot;normal&quot;
        ///     icon=&quot;http://popular.mb.skoda.vwg/siben/PC.ico&quot;
        ///     contextmenu=&quot;yes&quot;
        ///     sysmenu=&quot;yes&quot;
        ///     MINIMIZEBUTTON=&quot;yes&quot; 
        ///     caption=&quot;yes&quot;             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Najdi_PC {
            get {
                return ResourceManager.GetString("Najdi_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toFind=inputbox(&quot;Zadejte přímení (bez háčků a čárek) nebo DZCxxxx&quot;)
        ///&apos;inputbox &quot;Nalezeno:&quot;,, GetUserPath(toFind)
        ///msgbox GetUserPath(toFind),,&quot;Nalezené údaje:&quot;
        ///
        ///
        ///function GetUserPath(username)
        ///  Const ADS_SCOPE_SUBTREE = 3
        ///  Set objConnection = CreateObject(&quot;ADODB.Connection&quot;)
        ///  Set objCommand =   CreateObject(&quot;ADODB.Command&quot;)
        ///  objConnection.Provider = &quot;ADsDSOObject&quot;
        ///  objConnection.Open &quot;Active Directory Provider&quot;
        ///  Set objCOmmand.ActiveConnection = objConnection
        ///  &apos;objCommand.CommandText = &quot;Sel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NajdiDZC {
            get {
                return ResourceManager.GetString("NajdiDZC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;MIRAS information SCRIPT&lt;/title&gt;
        ///  
        ///   &lt;STYLE&gt;
        ///    H1, H3 { color: green }
        ///  &lt;/STYLE&gt;
        ///
        ///
        ///	&lt;script language=&quot;VBScript&quot;
        ///	        type=&quot;text/vbscript&quot;&gt;
        ///&apos;*************************************************
        ///Option Explicit &apos;nucená deklarace promněnných
        ///
        ///Dim Text, Title
        ///Dim WshNetwork, oDevices,  oDrives, myOlApp      &apos; Object variable
        ///Dim key1, i, myNameSpace
        ///Dim WshShell
        ///Dim fso, oDrive, wsh, Shell, drive      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PC_INFO {
            get {
                return ResourceManager.GetString("PC_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PsExec {
            get {
                object obj = ResourceManager.GetObject("PsExec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RegSearch {
            get {
                object obj = ResourceManager.GetObject("RegSearch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RemoteDialog {
            get {
                object obj = ResourceManager.GetObject("RemoteDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem Tento skript slouzi pro spusteni s parametrem, ktery obsahuje jmeno suoboru napr. &quot;runpwshell_parameter /muj_Skript.ps1&quot;
        ///@echo off
        ///set curdir=%~dp0%
        ///pushd %curdir%
        ///title TechnolToolkit
        ///color 0e
        ///cls
        ///PowerShell -NoProfile -ExecutionPolicy Bypass -File &quot;.\%1&quot; %2 -debug true -simulate false.
        /// </summary>
        internal static string runpwshell_parameter {
            get {
                return ResourceManager.GetString("runpwshell_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VAS6154 {
            get {
                object obj = ResourceManager.GetObject("VAS6154", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Script ktery emuluje ipconfig /all command.  A pote vylistuje sitove disky. 
        ///&apos;MiK
        ///
        ///Dim strComputer, CRLF
        ///Dim colDrives, strMsg
        ///Dim WSHNetwork
        ///
        ///strComputer = &quot;.&quot;
        ///CRLF = Chr(13) &amp; Chr(10)
        ///Set NetworkPROP = WScript.CreateObject(&quot;WScript.Network&quot;)
        ///Set objWMIService = GetObject _
        ///    (&quot;winmgmts:&quot; &amp; &quot;!\\&quot; &amp; strComputer &amp; &quot;\root\cimv2&quot;)
        ///Set colAdapters = objWMIService.ExecQuery _
        ///    (&quot;Select * from Win32_NetworkAdapterConfiguration Where IPEnabled = True&quot;)
        ///
        ///
        ///For Each objAdapter in colAdapters
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zjistit_IPconfig {
            get {
                return ResourceManager.GetString("Zjistit_IPconfig", resourceCulture);
            }
        }
    }
}
